---
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - APP_URL=https://docs.local.yasco.tech
      - APP_KEY=${APP_KEY}
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=sync
      - APP_THEME=custom
    volumes:
      - ./app_config:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bookstack.rule=Host(`docs.local.yasco.tech`)"
      - "traefik.http.routers.bookstack.entrypoints=websecure"
      - "traefik.http.routers.bookstack.tls=true"
      - "traefik.http.routers.bookstack.tls.certresolver=letsencrypt"
      - "traefik.http.services.bookstack.loadbalancer.server.port=80"
    networks:
      - frontend
      - backend
    restart: unless-stopped
    depends_on:
      - bookstack-db

  bookstack-db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack-db
    environment:
      - PUID=2001
      - PGID=2001
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Jakarta
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./db_data:/config
    networks:
      - backend
    restart: unless-stopped

networks:
  frontend:
    external: true
  backend:
    driver: bridge