---
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack:latest
    container_name: bookstack
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - APP_URL=https://localhost:8443 # or use HTTP http://localhost:8080
      - APP_KEY=${APP_KEY}
      - DB_HOST=bookstack-db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=sync
      - APP_THEME=custom
    volumes:
      - ./app_config:/config
    restart: unless-stopped
    depends_on:
      - bookstack-db

  bookstack-db:
    image: lscr.io/linuxserver/mariadb
    container_name: bookstack-db2
    environment:
      - PUID=2001
      - PGID=2001
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=Asia/Jakarta
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/config
    restart: unless-stopped

volumes:
  db_data: