---
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9090:9090"
    environment:
      MINIO_ROOT_USER: ${ROOT_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${ROOT_SECRET_KEY}
    volumes:
      - minio-data:/data
    command: server --console-address ":9090" /data

volumes:
  minio-data: